title:              Alfred Prah
email:              alfredprah@gmail.com
description:        "Senior Data Scientist<br><br>CTO @ <a href='https://carwiz.ai/' target='_blank' style='color: white;'><u>CarWiz.ai</u></a>"
author:             Alfred Prah
baseurl:            ""
url:                "https://alfredprah.github.io/"      

# Social Profiles
twitter_username:   
github_username:    alfredprah
facebook_username:  
instagram_username:  
linkedin_username:  alfredprah

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
# theme: jekyll-theme-clean-blog
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-theme-clean-blog
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# include: 
#   - _pages
