title:              Alfred Prah
email:              alfredprah@gmail.com
# description:        "Data Science<br><br>AI Engineering <br><br> Checkout my latest project, <a href='https://genaibro.com/' target='_blank' style='color: white;'><u>GenAIBro</u></a>"
description:        "<span style='color: #FFD700;'>Data Science</span><br><br><span style='color: #FFD700;'>AI Engineering</span><br><br>Checkout my latest project, <a href='https://genaibro.com/' target='_blank' style='color: gold;'><u>GenAIBro</u></a>"
author:             Alfred Prah
baseurl:            ""
url:                "https://alfredprah.github.io/"      

# Social Profiles
twitter_username:   
github_username:    alfredprah
facebook_username:  
instagram_username:  
linkedin_username:  alfredprah

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
# theme: jekyll-theme-clean-blog
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-theme-clean-blog
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# include: 
#   - _pages
